version: "3"
services:
  db:
    image: "postgres:13"
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "my_password"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
      #starts with 0 because the execution order is in alphabetical order
      - ./init_schema.sql:/docker-entrypoint-initdb.d/0_schema.sql
      - ./ddl/fundamentals.sql:/docker-entrypoint-initdb.d/fundamentals.sql
      - ./ddl/prices.sql:/docker-entrypoint-initdb.d/prices.sql
      - ./ddl/prices_split_adjusted.sql:/docker-entrypoint-initdb.d/prices_split_adjusted.sql
      - ./ddl/securities.sql:/docker-entrypoint-initdb.d/securities.sql
volumes:
  my_dbdata: