version: "3.8"
services:
  framework:
    build: ./Dockerfile
    ports:
      - '3000:3000'
  postgres:
    image: "postgres:13"
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "my_password"
    ports:
      - "54320:5432"
    volumes:
      - data:/data/db
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    env_file:
      - ./env/mssql.env
    ports:
      - 14330:1433
    volumes:
      - data:/data/db
  metadata:
    image: "postgres:13"
    container_name: "metadata"
    environment:
      POSTGRES_DB: "metadata"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "54320:5432"
    volumes:
      - data:/data/db
volumes:
  data: