version: "3.8"
services:
  framework:
    build: .
    image: my_custom_framework_image:latest
    container_name: ep_demo
    volumes:
      #- /Users/robert.nemeth/Documents/private/db_type_ingestion:/framework
      - ./utils:/framework/utils
      - ./test.py:/framework/test.py
      - ./data:/framework/data
    ports:
      - "4000:80"
    depends_on:
      - postgres
      - mssql
      - metadata
  postgres:
    image: "postgres:13"
    container_name: "my_postgres"
    env_file:
      - ./env/postgres.env
    ports:
      - "54320:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    env_file:
      - ./env/mssql.env
    ports:
      - 14330:1433
    volumes:
      - mssql-data:/var/opt/mssql
  metadata:
    image: "postgres:13"
    container_name: "metadata"
    env_file:
      - ./env/metadata.env
    ports:
      - "54321:5432"
    volumes:
      - metadata-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  mssql-data:
  metadata-data: