version: "3"
services:
  db:
    image: "postgres:13"
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "my_password"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
      - ./init_schema.sql:/docker-entrypoint-initdb.d/0_schema.sql
      - ./ddl/market_data.sql:/docker-entrypoint-initdb.d/market_data.sql
volumes:
  my_dbdata: